spring:
  application:
    name: "eagle-bank"
  datasource:
    url: "jdbc:h2:mem:eaglebankdb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"
  sql:
    init:
      mode: always